name: Manual NPM Publish for TS SDK

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      #################################
      # npm
      #################################

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish
        run: npm publish --access public

      #################################
      # yarn
      #################################

      # - name: Install yarn
      #   run: npm install --global yarn && yarn --version

      # - name: Publish
      #   run: yarn publish

      #################################
      # pnpm
      #################################

      # - name: Install pnpm
      #   run: npm install -g pnpm@latest-10

      # - name: Publish
      #   run: pnpm publish --no-git-checks

      #################################
      # composite action
      #################################

#      - name: Publish
#        uses: smartcontractkit/.github/actions/ci-publish-npm@5cf24eba2fef708acd6050f0f9a0397b2dabbfb8
#        with:
#          publish-command: npm publish
#          package-json-directory: ./typescript
